
Gem::Specification.new do |spec|
  spec.required_ruby_version = '>= 2.5.0'
end

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 20

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'

