AllCops:
  NewCops: enable
  DisabledByDefault: true
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'

require:
  - rubocop-performance
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 20


