development:
  HOST: 'http://localhost:3002'
  STUDY_SITE_HOST: 'http://localhost:3000'
  PORT: '3002'

test:
  HOST: 'http://localhost:3000'
  STUDY_SITE_HOST: 'http://localhost:3000'
  PORT: '3002'
