name: CI - To check on linters and run test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  
  linters:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: bundle exec rubocop

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: bundle exec rspec
